### ISSUE TITLE
lzma.LZMAFile: TemporaryFile instance has no attribute 'seekable'

### ISSUE THREAD

**Issue by mgorny** [peterjc/backports.lzma#10]
Long story short, `seekable()` is not a part of official `file` object API in Python 2.7. In particular, `TemporaryFile` and subclasses don't have that, and therefore `LZMAFile` fails on them. You shouldn't rely on undocumented methods for the backport.

Reference: https://docs.python.org/2/library/stdtypes.html#file-objects

**Comment by peterjc** [comment]
Do you have an alternative suggestion?

**Comment by mgorny** [comment]
Nothing really specific. For `seekable()` implementation, I guess we can leave it as-is since if someone expects that method in `LZMAFile`, he can also expect it in underlying file. But in other places, all I can think of is just trying without testing. Maybe make `self._check_can_seek()` no-op if underlying file does not provide `seekable()`.

**Comment by peterjc** [comment]
I'm about to archive this repository, and so am closing the outstanding issues and pull requests. Thank you for your efforts though.
