### ISSUE TITLE
Windows wheels available

### ISSUE THREAD

**Issue by carlkl** [peterjc/backports.lzma#14]
In case of interest: windows wheels for (py-2.6 and py-2.7) of backports.lzma are provided at:
https://anaconda.org/carlkl/backports.lzma

install it with:

`pip install -i https://pypi.anaconda.org/carlkl/simple backports.lzma`

**Comment by peterjc** [comment]
Thanks @carlkl - How would I go about compiling these Windows wheels myself for upload to PyPI?

(This is something I've yet to tackle, but the pip ecosystem seems mature now enough to make it worthwhile)

**Comment by Jellyfrog** [comment]
@carlkl could you bump to 0.0.6? And also answer peterjcs question :)

**Comment by patter001** [comment]
Any chance someone has manylinux versions of the wheels ?

**Comment by peterjc** [comment]
Again, I've not previously built manylinux wheels (but want to for another project), so if anyone can guide me here I'm very happy to upload them to PyPI.

**Comment by bdewilde** [comment]
Hi @peterjc, have you seen this guide to Python packaging? There's a section on platform-specific wheels which might be helpful: https://packaging.python.org/distributing/#wheels

I have `backports.lzma` as a dependency in [textacy](https://github.com/chartbeat-labs/textacy), but it's apparently not installing on Windows. I'd love to maintain Py2 compatibility on lzma compression, but don't know how to debug this issue. Thanks in advance for any help you can provide!

**Comment by peterjc** [comment]
I still haven't ever used ``backports.lzma`` on Windows. The only Windows machine I have direct access to is an elderly 32-bit Windows XP machine, but if that worked it should be fine for building wheels for 32bit Python 2.5, 2.6, 2.7 (and if needed early versions of Python 3, but Python 3.5 onwards won't install on this old OS).

@carlkl managed to figure out how to compile ``backports.lzma`` on a version of Windows...

**Comment by jakirkham** [comment]
Do you have some steps to follow @peterjc? I'd like to also build this for Windows, but am struggling.

**Comment by carlkl** [comment]
Sorry for my late reply:

I made (almost a year ago)  the following steps using `mingwpy`

first build `xz-5.2.2` 
```
configure --enable-static --disable-shared --disable-rpath --disable-lzma-links --prefix=<PATH>
make
make install
```
then 
```
python setup.py bdist_wininst
wheel convert dist/*.exe
```

Nevertheless, at that time I had problems to unpack some archives with backports.lzma so I didn't follow it further.

**Comment by jakirkham** [comment]
Thanks @carlkl.

**Comment by nehaljwani** [comment]
Hello folks, I have an all-tests-passing windows build with a PR at https://github.com/peterjc/backports.lzma/pull/25

**Comment by peterjc** [comment]
Thanks to #25 from @nehaljwani, we should now have automated test builds working under Windows using AppVeyor.

I would hope to issue a new release shortly with this and a version bump applied.

Leaving this issue open until we have Windows Wheels up on PyPI.

**Comment by jakirkham** [comment]
It should be possible to use `conda-build` to produce wheels from a `conda` recipe.

**Comment by peterjc** [comment]
@jakirkham, @nehaljwani : Would either of you be willing to build the Windows wheels (once I've done a version bump for this - either v0.0.9 or go straight to v1.0.0 which seems justified here as we finally have all three major platforms supported)? I could then upload them to PyPI.

**Comment by nehaljwani** [comment]
To be honest, I don't have much experience building wheels.

For the wheels, I have the following questions:
- Would the linking to liblzma be static or dynamic in the wheel?
- For the windows wheels, for py27, we have no choice, but to use the mingw build. But for py35, py36 we have a choice. Which one should we choose?

**Comment by peterjc** [comment]
Because this is a back-port, the wheels for Python 3.3 onwards are not so important. It is Python 2.7 we care most about.

I would think for practicality on Windows, we should static link liblzma so that the end user does not need to install that themselves - they can just do ``pip install backports.lzma`` and be done.

**Comment by carlkl** [comment]
BTW:

in `setup.py` I strongly  recommend to use `"-mincoming-stack-boundary=2"` instead of `"-mstackrealign"`:

```python
class build_ext_subclass(build_ext):
    def build_extensions(self):
        xtra_compile_args = []

        if self.compiler.compiler_type == "mingw32":
            xtra_compile_args = [
                       "-DMS_WIN32",
                       "-mincoming-stack-boundary=2"
                       ] if is32bit else ["-DMS_WIN64"]
```

I cannot easily create a PR right now - sorry for that.

In `appveyor.yml` it should be easy to perform the: download xz; configure; install steps as described in  https://github.com/peterjc/backports.lzma/issues/14#issuecomment-281441697 to produce a static library `liblzma.a`. This should be possible with the mingw-w64 version of appveyor as well.

**Comment by mingwandroid** [comment]
I'd rather annotate only the exact functions that can be called by the Python interpreter with `__attribute__((force_align_arg_pointer))` than slowing them all down unnecessarily.

**Comment by mingwandroid** [comment]
FWIW, I used to use `-mincoming-stack-boundary=2` but found it unreliable so I switched to `-mstackrealign` which has never failed for me.

**Comment by carlkl** [comment]
I've had experience of exactly the opposite, but I cannot remember the details. BTW: Openblas has been useing `-mincoming-stack-boundary=2` for the 32bit builds for years.

**Comment by carlkl** [comment]
I loosly remember on problems combining `-mstackrealign` and `-O2`, but this was with gcc-4.8. It is a fact, that prolog code emitted be `-mincoming-stack-boundary=2` is ugly. However it seems to me a rock solid solution to combine MSVC object code with gcc object code on x86.

**Comment by carlkl** [comment]
@mingwandroid, you mentioned usage of `-mincoming-stack-boundary=2` in https://github.com/conda-forge/conda-forge.github.io/issues/112#issuecomment-217252709 . I would be really be interested on known problems with this flags.

@peterjc, I recommend to still use `-mstackrealign` and change to `-mincoming-stack-boundary=2` if you encounter problems.

**Comment by peterjc** [comment]
I'm personally not using this on Windows, but will keep that in mind if and when we get any bug reports.

(Since we still don't have wheels on PyPI, the audience is self selective for the more technical Windows Python users)

**Comment by jakirkham** [comment]
Regarding wheels, you may find this discussion interesting. ( https://github.com/conda-forge/conda-smithy/issues/608 )

**Comment by thedrow** [comment]
I just bumped into this in [my build](https://ci.appveyor.com/project/ask/kombu/builds/23560019/job/07o28aw3k5g8qk2p).
It's possible to build wheels on AppVeyor and uploading them to PyPi.
Would you mind uploading the wheels for the latest release if I contributed a patch to build and store them?

**Comment by peterjc** [comment]
Adding wheel building to https://github.com/peterjc/backports.lzma/blob/master/.appveyor.yml would be great, and if you have a cunning plan for storing them in order to upload to PyPI, even better.

For the NumPy ecosystem, they have some hosting on rackspace used as a staging area for wheels from AppVeyor etc - I could ask if we could use that?

**Comment by thedrow** [comment]
See https://github.com/google/brotli-wheels/blob/master/appveyor.yml#L97 and https://www.appveyor.com/docs/how-to/secure-files/ to encrypt the credentials.

The deploy will happen when tagging.

**Comment by peterjc** [comment]
+1 for deploy direct to PyPI on tagging

With TravisCI we can do secure environment variables like API keys or here the PyPY password. Something which works for TravisCI and AppVeyor would be ideal.

Anyway, working wheel building is the first hurdle.

**Comment by nehaljwani** [comment]
I have a PR at https://github.com/peterjc/backports.lzma/pull/38 to create wheels. I uploaded a few at: https://anaconda.org/nehaljwani/backports.lzma/files

**Comment by peterjc** [comment]
With #38 merged, assuming the  wheels at https://anaconda.org/nehaljwani/backports.lzma/files work nicely, we can probably try adding a deploy to the script following the approach suggested by @thedrow

**Comment by nehaljwani** [comment]
One can try out the wheels with:
```
pip install -i https://pypi.anaconda.org/nehaljwani/simple backports.lzma
```

**Comment by thedrow** [comment]
The wheels work just fine.
Please release them.

**Comment by peterjc** [comment]
I'm about to archive this repository, and so am closing the outstanding issues and pull requests. Thank you for your efforts though.
