### ISSUE TITLE
format argument not working

### ISSUE THREAD

**Issue by conduit242** [peterjc/backports.lzma#21]
When using lzma.compress, it doesn't seem possible to pass the _format_ argument. For example:
lzma.compress(data, format=FORMAT_RAW)
yields:
NameError: name 'FORMAT_RAW' is not defined

Same for the default, FORMAT_XZ:
NameError: name 'FORMAT_XZ' is not defined

**Comment by peterjc** [comment]
That looks like you've not imported/defined ``FORMAT_RAW`` into your namespace (this or a typo is the usual cause of a ``NameError`` I find).

You almost certainly just need to write ``lzma.FORMAT_RAW`` and everything will be fine.
