### ISSUE TITLE
backports/lzma/_lzmamodule.c(115) : fatal error C1083: Cannot open include file: 'lzma.h': No such file or directory

### ISSUE THREAD

**Issue by cirmic** [peterjc/backports.lzma#22]
I have a Windows 7 PC with Visual Studio 2015 upgrade 3 installed on it and I would like to install backports.lzma library for Python with pip.

I have downloaded and extracted XZ Utils in Program Files folder. (XZ Utils is mandatory for install backports library as specified from [Pypi site](https://pypi.python.org/pypi/backports.lzma/) )

This is the pip output:

> Installing collected packages: backports.lzma
> Running setup.py install for backports.lzma: started
> Running setup.py install for backports.lzma: finished with status 'error'
> Complete output from command "C:\Program Files (x86)\Python27\python.exe" -u -c "import setuptools, tokenize;__file__='c:\\users\\myuser\\appdata\\local\\temp\\pip-build-smbn4k\\backports.lzma\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\myuser\appdata\local\temp\pip-hfgg8w-record\install-record.txt --single-version-externally-managed --compile:
> This is backports.lzma version 0.0.8
> running install
> running build
> running build_py
> creating build
> creating build\lib.win32-2.7
> creating build\lib.win32-2.7\backports
> copying backports\__init__.py -> build\lib.win32-2.7\backports
> creating build\lib.win32-2.7\backports\lzma
> copying backports\lzma\__init__.py -> build\lib.win32-2.7\backports\lzma
> running build_ext
> building 'backports/lzma/_lzma' extension
> creating build\temp.win32-2.7
> creating build\temp.win32-2.7\Release
> creating build\temp.win32-2.7\Release\backports
> creating build\temp.win32-2.7\Release\backports\lzma
> C:\Users\myuser\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG "-IC:\Program Files (x86)\Python27\include" -IC:\Users\myuser\include -I/opt/local/include -I/usr/local/include "-IC:\Program Files (x86)\Python27\include" "-IC:\Program Files (x86)\Python27\PC" /Tcbackports/lzma/_lzmamodule.c /Fobuild\temp.win32-2.7\Release\backports/lzma/_lzmamodule.obj
> _lzmamodule.c
> backports/lzma/_lzmamodule.c(32) : warning C4273: 'PyErr_NewExceptionWithDoc' : inconsistent dll linkage
>         C:\Program Files (x86)\Python27\include\pyerrors.h(226) : see previous definition of 'PyErr_NewExceptionWithDoc'
> backports/lzma/_lzmamodule.c(115) : fatal error C1083: Cannot open include file: 'lzma.h': No such file or directory
> error: command 'C:\\Users\\myuser\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\cl.exe' failed with exit status 2
> 
> ----------------------------------------
> Failed building wheel for backports.lzma
> Command ""C:\Program Files (x86)\Python27\python.exe" -u -c "import setuptools, tokenize;__file__='c:\\users\\myuser\\appdata\\local\\temp\\pip-build-smbn4k\\backports.lzma\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\myuser\appdata\local\temp\pip-hfgg8w-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\myuser\appdata\local\temp\pip-build-smbn4k\backports.lzma\
> 'backports.lzma' failed to install. Exit code: 1 

However in `Program Files\xz\include` there is the `lzma.h` file. 
How to link the header to be recognized?

**Comment by peterjc** [comment]
I do not currently have access to a Windows development machine to try this on.

However, in somewhat lucky timing, yesterday and today I have been experimenting with AppVeyor, and while I'm currently stuck I know how to solve the current issue.

By default the ``setup.py`` will look for ``lzma.h`` under ``$HOME/include/lzma.h`` so the simple answer is put this under your home folder rather than under "Program Files". Since there are no explicit recommendations on where to unzip that folder, this is a sensible option you'll certainly have write permissions here.

Assuming you didn't compile liblzma yourself, you will likely need to move the DLLs from the platform specific files to ``$HOME/lib/`` instead, i.e. for 32-bit:

```
cp C:/Users/YOURNAME/bin_i686/liblzma.* C:/Users/YOURNAME/lib/"
```

Or for 64 bit:

```
cp C:/Users/YOURNAME/bin_x86-64/liblzma.* C:/Users/YOURNAME/lib/"
```

At this point I began to run into trouble with linking, and am currently stuck.

See https://ci.appveyor.com/project/peterjc/backports-lzma/build/ and my AppVeyor configuration file on this branch https://github.com/peterjc/backports.lzma/blob/appveyor/.appveyor.yml

Over on #14 it was reported that ``backports.lzma`` could be compiled on Windows using a self-compiled liblzma.

**Comment by jakirkham** [comment]
There is an AppVeyor build proposed in PR ( https://github.com/peterjc/backports.lzma/pull/25 ).

**Comment by fireattack** [comment]
This seems still an issue. Is there any other way to install it on Windows? The wheel version (#14) is still 0.03.

**Comment by peterjc** [comment]
You can use conda, the conda-forge packages include Windows builds and cover Python 2.7, 3.5 and 3.6 at the time of writing: https://anaconda.org/conda-forge/backports.lzma

**Comment by cgohlke** [comment]
> Is there any other way to install it on Windows? The wheel version in #14 (0.0.3) seems to work, but very outdated.

Up-to-date wheels for Python 2.7, 3.4, 3.5, 3.6, and 3.7 are at <https://www.lfd.uci.edu/~gohlke/pythonlibs/#backports.lzma>

**Comment by fireattack** [comment]
Thank you!

**Comment by peterjc** [comment]
I'm about to archive this repository, and so am closing the outstanding issues and pull requests. Thank you for your efforts though.
