### ISSUE TITLE
Use macOS's included liblzma?

### ISSUE THREAD

**Issue by peterjc** [peterjc/backports.lzma#24]
Cross reference https://github.com/samtools/htslib/pull/628

Apparently a vanilla macOS installation in fact includes ``/usr/lib/liblzma.dylib`` but sadly does not ship the corresponding header files. We could in principle include a fake ``lzma_stub.h`` header that provides just enough declarations so that the Python lzma wrapper can be compiled, for use if we have a usable ``liblzma`` but no ``lzma.h``. This may require trickery in our ``setup.py`` to achieve this...

**Comment by jakirkham** [comment]
If this does happen, it would be nice to have an option to override this and use our own LZMA. This is of particular importance for package managers.

**Comment by peterjc** [comment]
Good point. If you know anyone looking after a macOS package of this back port who might be able to advise on this, please point them at this issue.

**Comment by peterjc** [comment]
I'm about to archive this repository, and so am closing the outstanding issues and pull requests. Thank you for your efforts though.
