### ISSUE TITLE
setup.py broken on PyPy

### ISSUE THREAD

**Issue by mgorny** [peterjc/backports.lzma#26]
The most recent version seems to be broken on PyPy:

```
Collecting backports.lzma
  Using cached backports.lzma-0.0.9.tar.gz
    Complete output from command python setup.py egg_info:
    This is backports.lzma version 0.0.9
    Traceback (most recent call last):
      File "<module>", line 1, in <module>
      File "/tmp/pip-build-OiRNki/backports.lzma/setup.py", line 32, in <module>
        is32bit = tuple.__itemsize__ == 4
    AttributeError: type object 'tuple' has no attribute '__itemsize__'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-OiRNki/backports.lzma/
```

You seem to be accessing deep internals of CPython which looks like a very, very bad idea.

**Comment by peterjc** [comment]
@mgorny Are you using macOS perhaps? We've got Linux and Windows covered now via TravisCI and AppVeyor, but I neglected to run this by hand on macOS. Apologies, with hindsight this was an obvious oversight.

@nehaljwani any objections to this tweak to your Windows specific changes?

**Comment by peterjc** [comment]
Cross reference pull request #27.

@mgorny would you like to expand the TravisCI setup to include PyPy?

**Comment by mgorny** [comment]
Nope, I don't have any Macs.

And yes, I wanted to post PyPy PR once this bug is fixed.

**Comment by nehaljwani** [comment]
No objections from my side. Apologies for replying late. Timezones :(

**Comment by peterjc** [comment]
This should be closed as soon as I make another release - having TravisCI include PyPY first seems a good idea though.

**Comment by peterjc** [comment]
Good news, ``setup.py`` works again under pypy v5.7.1 (i.e. Python 2).  Bad news, tests fail - see https://travis-ci.org/peterjc/backports.lzma/jobs/325435420

```
======================================================================
ERROR: test_bad_args (__main__.CompressDecompressFunctionTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_lzma.py", line 273, in test_bad_args
    b"", format=lzma.FORMAT_RAW, filters={})
  File "/opt/python/pypy-5.7.1/lib-python/2.7/unittest/case.py", line 473, in assertRaises
    callableObj(*args, **kwargs)
  File "/home/travis/virtualenv/pypy-5.7.1/site-packages/backports/lzma/__init__.py", line 463, in decompress
    decomp = LZMADecompressor(format, memlimit, filters)
LZMAError: Internal error
----------------------------------------------------------------------
```

Also fails the same way on pypy 5.8.0, https://travis-ci.org/peterjc/backports.lzma/jobs/325437043

I guess I should try backports.lzma v0.0.8 for comparison...

And it fails in a different way on pypy3 version 5.8.0-beta0 https://travis-ci.org/peterjc/backports.lzma/jobs/325435421

```
$ python test_lzma.py
Traceback (most recent call last):
  File "test_lzma.py", line 35, in <module>
    from backports import lzma
  File "/home/travis/virtualenv/pypy3.5-5.8.0/site-packages/backports/lzma/__init__.py", line 25, in <module>
    from ._lzma import *
ImportError: /home/travis/virtualenv/pypy3.5-5.8.0/site-packages/backports/lzma/_lzma.pypy3-58-x86_64-linux-gnu.so: undefined symbol: PyUnicode_DecodeUTF8Stateful
```

I'd like to try this on the latest pypy3 before investigating that any further.

**Comment by peterjc** [comment]
TravisCI testing under pypy2 and pypy3 implemented as of 17b9388aeec20380c052453e8601a5e3273cd4a1 - both are marked as allowed failures for now.

**Comment by peterjc** [comment]
@mgorny did you ever run the tests under PyPy? Did they work before?

(I don't have PyPy on this machine and probably won't have time to look into this any further today, maybe next week though)

**Comment by mgorny** [comment]
Well, given that I didn't enable pypy on this package in Gentoo before (and I've definitely looked into it) and yet setup.py didn't fail back then, then I'm going to guess that they've failed for me ;-). On the other hand, I can tell that my gemato app passed its lzma/xz tests, so the issue isn't that major.

I'm going to do a few more runs today and see how they work. I already see that some of them are relying on more fancy liblzma features that I've disabled, so that would need another patch ;-).

**Comment by peterjc** [comment]
Discussion about PyPy support continued on old issue #5 as spotted by @mgorny - leaving this open until I do another release with the updated ``setup.py`` file.

**Comment by peterjc** [comment]
OK, v0.0.10 is up on PyPy which should fix this - thank you to @mgorny 
https://pypi.python.org/pypi/backports.lzma/0.0.10
