### ISSUE TITLE
Splitting .py from .so

### ISSUE THREAD

**Issue by jayvdb** [peterjc/backports.lzma#37]
I've been packaging this for openSUSE, and needed to manually split the package into two parts, one for sitelib and the other for sitearch.

The primary problem is that if PyPi package `backports`, or any other `backports.foo` module is installed, there is reasonable chance that they are installed into the arch-independent site-packages area, while this package will be installed into the arch-dependent site-packages.  And Python 2 doesnt handle the same package appear in both, so the top level `backports` appearing in both is problematic.  Many installs of Python have one area for both - the split is more typical in distro installs, where separating arch from non-arch files is important.

To solve this, I manually move the backports/lzma/__init__.py into sitelib , and move the `_lzma.so` out of the `backports` namespace, to the top level of sitearch.

You can see the .spec at https://build.opensuse.org/package/show/home:jayvdb:py-backports/python-backports.lzma , and the build logs are also there if you login to OBS.

I believe (but not 100% sure) this can be fixed in setup.py, and I am happy to do that, if the maintainers are happy to have the dso moved to the top level.  There is likely some extra voodoo needed to tell setuptools that the package is using two top level namespaces.

If not, it is a fairly standard type of 'packaging' problem that doesnt need to be fixed here.

**Comment by peterjc** [comment]
I’m just replying from reading the email alone while on leave (I have not
looked at the changes needed), but my initial thought is to leave this
complexity to the packaging teams as required.

I’d rather spend any time I can make for this project on the Windows wheels
and not risk breaking things with a major rearrangement.

Sorry, that’s probably not what you were hoping for. It might be worth
logging an issue at the parent backports namespace repository as this issue
is broader than just LZMA?

Peter

**Comment by jayvdb** [comment]
Thanks for the response.  Glad to know you are not interested, so I dont waste both our times.  It is a bug because this package doesnt interact well with other backports, but I can appreciate it is very low priority as it mostly effects distro users who are not in a venv or pipenv, etc, and distros can solve the problem by packaging this library similar to the way I have.

The backports namespace package could document this problem better, maybe on the PyPI page, but I doubt many people read that carefully.

fwiw, the main scandir backport isnt in the backports namespace.

I have tried to find and package every `backports.*` (except backports.ssl which I wouldnt dare touch), and this appears to be the only arch specific one.

**Comment by peterjc** [comment]
I'm about to archive this repository, and so am closing the outstanding issues and pull requests. Thank you for your efforts though.
