### ISSUE TITLE
test_lzma.py ImportError: cannot import name lzma

### ISSUE THREAD

**Issue by dafuki** [peterjc/backports.lzma#44]
On Debian 10, python 2.7 I get this error after installing backports.lzma

`Traceback (most recent call last):
  File "test_lzma.py", line 35, in <module>
    from backports import lzma
ImportError: cannot import name lzma`

Any idea what is wrong?
Installed Ubuntu 18 LTS and it seems to be working

**Comment by peterjc** [comment]
You may not have actually installed it? I'd need more details on how exactly you did that and ran the tests. This could be something subtle like you have more than one copy of python on your system (e.g. you did "pip install ..." which used Python A, but "python test_lzma.py" which used Python B).

**Comment by dafuki** [comment]
Hey, thanks for replying.
I used both pip to install it and install from source

Can't recall right now what excatly I did but I'm pretty sure it was 
`pip install backports.lzma
apt-get install liblzma-dev`

Also tried the way it's documented from github sources
`$ git clone git://github.com/peterjc/backports.lzma.git
$ cd backports.lzma
$ python setup.py install
$ cd test
$ python test_lzma.py`

I'm not sure it has something to do with two python versions being install as the same situation was met with the Ubuntu 18 LTS.

Forgot to mention I tried this on two different Debian 10 machines.

**Comment by peterjc** [comment]
If there are two pythons, sometimes ``pip`` is linked to a different Python to the one called by ``python`` on the command line. That gets very confusing, so you can turn to ``python -m pip install backports.lzma`` instead.

However, you also tried "python setup.py install" which again should use the same python as "python test_lzma.py", so I am not optimistic that will solve this.

Can you run ``python -c "import backports; print(backports.__file__)"`` and look in the folder it reports? For example, on macOS under Python via conda:

```
$ python -c "import backports; print(backports.__file__)"
/Users/xxx/miniconda3/lib/python3.7/site-packages/backports/__init__.py
$ ls /Users/xxx/miniconda3/lib/python3.7/site-packages/backports/
__init__.py	__pycache__	lzma
$ python -c "from backports import lzma; print(lzma.__file__)"
/Users/pc40583/xxx/lib/python3.7/site-packages/backports/lzma/__init__.py
```

Have you installed any other backports? There could be a conflict (the above should be instructive in that case).

Something else to check is if the environment variable PYTHONPATH has been altered.

**Comment by dafuki** [comment]
Sorry for the late reply.

`$ python -c "import backports; print(backports.__file__)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute '__file__'`

Might be python 2.7 samantics, maybe __file__ is only in python 3?

**Comment by peterjc** [comment]
Strange ``__file__`` should be there on Python 2 as well https://docs.python.org/2/reference/datamodel.html

**Comment by dafuki** [comment]
Seems like some debian python package issue.
Under ubuntu 18 LTS I'm getting 
`$ python -c "import backports; print(backports.__file__)"

/usr/local/lib/python2.7/dist-packages/backports/__init__.pyc`

**Comment by peterjc** [comment]
I'm about to archive this repository, and so am closing the outstanding issues and pull requests. Thank you for your efforts though.
