### ISSUE TITLE
lzma sometimes fails to decompress a file

### ISSUE THREAD

**Issue by vnummela** [peterjc/backports.lzma#6]
Bacports.lzma fails to decompress some files, even though a direct call to XZ Utils will process the same files without complaints.

System details:
OS X 10.9.3
Python 2.7.7 via Anaconda 2.0.0
backports.lzma 0.0.2 (Just noticed there is a new version, but couldn't be bothered with the installation if it is only for the unicode support.)

Unfortunately I don't have Py3 installed and cannot therefore tell if this is an issue of the backported or the original version. I'm putting the issue here in order to get started somewhere.

Example data files:
This one fails:
https://dl.dropboxusercontent.com/u/90169773/lzma_issue/22h_ticks_bad.bi5
This one is processed without errors:
https://dl.dropboxusercontent.com/u/90169773/lzma_issue/23h_ticks_good.bi5

Attempting to decompress the 'bad' file raises the following error:
EOFError: Compressed file ended before the end-of-stream marker was reached.

The example files contain tick data and have been downloaded from the Dukascopy(.com) bank's historical economic data service. This error is relatively rare: Typically there are 1-5 failures per each 1000 data files. So far, all of them have been recoverable with XZ Utils. I have not detected any obvious pattern in which ones fail and which ones won't.

Heres a snippet of my program, including the xz workaround:

from **future** import print_function, division, absolute_import, unicode_literals
import os.path as op
import backports.lzma as lz
import subprocess

class whatever():

```
@staticmethod
def decompress(path):
    # Got data at all?
    if not op.isfile(path):
        raise Exception('Cannot find the .bi5 file!')
    try:
        # Regular decompression, ok most of the time
        with lz.open(path.encode('utf-8')) as f:
            filecontent = f.read()
    except EOFError:
        # back-up decompression via calling XZ Utils
        xz = '/usr/local/bin/xz -d --format=lzma --keep --suffix=.bi5 ' + '"' + path + '"'
        print('LZMA failed, falling back to XZ Utils for', path)
        __ = subprocess.call(xz.decode('utf-8'), shell=True)
        # The file should now be decompressed on disk. Strip the suffix and read it.
        with open(path[:-4], mode='r') as f:
            filecontent = f.read()
    return filecontent
```

**Comment by kenorb** [comment]
The same in here. See the following Travis [build](https://travis-ci.org/FX31337/FX-BT-Scripts/builds/82585604) which fails.

This happens on this [file](http://www.dukascopy.com/datafeed/EURUSD/2014/00/22/02h_ticks.bi5) each time.

In both Python 3.4 & 3.5.

**Comment by giuse88** [comment]
Check this out : 

http://stackoverflow.com/questions/37400583/python-lzma-compressed-data-ended-before-the-end-of-stream-marker-was-reached/37400585#37400585

@kenorb

**Comment by peterjc** [comment]
Sadly there does not seem to be any active work happening on the upstream issue http://bugs.python.org/issue21872

Assuming that does get fixed, we can apply the fix to the backport here.
